name = "nautica"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "06d1b6331dcb48018e5df3130307436f"
